# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28f7a14992934105dad67b9cf63aa684460ea714addc714a5a9f6978198fc532e409b5e4dfd7d0bed96bdbbc483cf08d472228d262aef33ef9dcbf2814e216b

test:
  secret_key_base: ffe706b5eca5aa742acbcbd63cf2a5652ac8c3d81cff173ac54185ec442cae27106d942d301a0b24e0452526aaa4950e7d6f8ba25504d886662579f66a86e703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
